- build.gradle
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/CaveatAliasNameMapper.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/CaveatAliasNameMapperTest.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/CaveatTestDataCreator.java
update to new probate-commons version 0.0.20 and rewrite of caveat alias name mapper
[ ] Yes
[x ] No
```
> Pro 4152 update probate commons version

- Jenkinsfile_CNP
> remove prod break

- build.gradle
- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/requirements.yaml
- src/main/java/uk/gov/hmcts/probate/security/SecurityConfiguration.java
- src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRO-4999
update java healthcheck.
add springboot healthcheck liveness
```
[ ] Yes
[x ] No
```
> Pro 4999 java health

- build.gradle
- docker/docker-compose-with-ccd.yml
- src/main/java/uk/gov/hmcts/probate/client/SubmitServiceApi.java
- src/main/java/uk/gov/hmcts/probate/client/SubmitServiceConfiguration.java
- src/main/java/uk/gov/hmcts/probate/core/service/IdentifierConfiguration.java
- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/CaveatMapper.java
- src/main/resources/application.yml
- src/test/java/uk/gov/hmcts/probate/core/service/SubmitServiceImplTest.java
- src/test/resources/caveatForm.json
change caveat from applicant email to applicationId
[ ] Yes
[ x] No
```
> PRO-5001: change caveat from applicant email to applicationId

- infrastructure/aat.tfvars
change to sidam url
[ ] Yes
[ x] No
```
> PRO-5085: change to sidam url

- build.gradle
change_commons_to_ver27
[ ] Yes
[x ] No
```
> PRO-5089_change_commons_to_ver27

- Jenkinsfile_CNP
- build.gradle
- charts/probate-orchestrator-service/values.aat.template.yaml
> retest liveness

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/requirements.yaml
- kubernetes/config.aat.yaml
> test integration

- charts/probate-orchestrator-service/requirements.yaml
- kubernetes/config.aat.yaml
> Pin Java chart version to 2.0.4

- Jenkinsfile_CNP
> unbreak prod deploy

- Jenkinsfile_CNP
- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/requirements.yaml
- charts/probate-orchestrator-service/values.template.yaml
> add sidam whitelisting

- src/contractTest/java/uk/gov/hmcts/probate/contract/tests/ProbateDocumentsControllerCoverSheetProviderTest.java
- src/contractTest/java/uk/gov/hmcts/probate/contract/tests/ProbateDocumentsControllerLegalDeclarationProviderTest.java
> Added new Invalid coversheet and legal decaration tests

- .gitignore
- Jenkinsfile_CNP
- dependency-check-suppressions.xml
- src/contractTest/java/uk/gov/hmcts/probate/contract/tests/ControllerProviderTest.java
- src/contractTest/resources/application.properties
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[x ] No
```
> FixPactVersioning issue

- Jenkinsfile_CNP
- build.gradle
- src/main/java/uk/gov/hmcts/insights/AppInsights.java
- src/main/resources/application.yml
PRO-5535: initial app insights config added
```
[ ] Yes
[x ] No
```
> PRO-5535: initial app insights config added

- infrastructure/main.tf
PRO-5535: add to main.tf app insights config added
```
[ ] Yes
[x ] No
```
> PRO-5535: add to main.tf app insights config added

- Jenkinsfile_CNP
PRO-5535: unbreaking jenkins build
```
[ ] Yes
[x ] No
```
> PRO-5535: unbreaking jenkins build

- src/main/java/uk/gov/hmcts/probate/core/service/CaseSubmissionUpdater.java
- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
- src/test/java/uk/gov/hmcts/probate/core/service/CaseSubmissionUpdaterTest.java
- src/test/java/uk/gov/hmcts/probate/core/service/SubmitServiceImplTest.java
Update application submitted date for caveat - on raising the caveat.
```
[ ] Yes
[X] No
```
> PRO-5580: Update application submitted date for caveat.

- Jenkinsfile_CNP
> test build

- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
Removed application submitted date update, until field is on the spreadsheet.
```
[ ] Yes
[X] No
```
> PRO-5580: Removed application submitted date update.

- Jenkinsfile_CNP
Stop pipeline breaking to prod.
```
[ ] Yes
[X] No
```
> PRO-5580: Stop pipeline breaking to prod.

- build.gradle
- dependency-check-suppressions.xml
> Pro 5641 update owasp

- src/main/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImpl.java
- src/test/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImplTest.java
set cav exp date from caveatRaised call to backoffice api
> PRO-5616: set cav exp date from bo notification call

- dependency-check-suppressions.xml
> Fixed PROD dependency check failures

- src/main/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImpl.java
- src/main/java/uk/gov/hmcts/probate/model/backoffice/BackOfficeCaveatData.java
- src/test/java/uk/gov/hmcts/probate/core/service/BackOfficeServiceImplTest.java
Added applicationSubmittedDate upon CaveatRaised, populated from data returned for send notifications
> PRO-5824: added applicationSubmittedDate for FE caveat creation

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/probate/controller/DocumentsController.java
> Check deployment

- charts/probate-orchestrator-service/values.aat.template.yaml
> add   aadIdentityName: probate

- charts/probate-orchestrator-service/values.aat.template.yaml
> disable idam pr

- charts/probate-orchestrator-service/values.aat.template.yaml
> disable idam pr properly

- Jenkinsfile_CNP
> Disable Legacy Deployment

- src/main/resources/application.yml
- src/main/resources/bootstrap.yaml
> modified bootstap to env. variable

- src/main/java/uk/gov/hmcts/probate/security/ServiceAuthConfiguration.java
> using same name

- Jenkinsfile_CNP
> Enable Legacy  Deployment ACS

- Dockerfile
- web.config
> Upgrade appinsights

- build.gradle
- src/main/java/uk/gov/hmcts/probate/controller/InvitationController.java
- src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
- src/main/java/uk/gov/hmcts/probate/service/BusinessService.java
- src/test/java/uk/gov/hmcts/probate/controller/InvitationControllerTest.java
- src/test/resources/invite/invitation.json
- src/test/resources/invite/invitationResend.json
https://tools.hmcts.net/jira/browse/PRO-4834
Add endpoint to invitation controller to get all invitations for all executors
```
[ ] Yes
[x] No
```
> Pro 4834 add get all invites endpoint

- dependency-check-suppressions.xml
> Fixed suppressions

- Dockerfile
- Jenkinsfile_CNP
> Testing App insights

- Dockerfile
- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/probate/security/ServiceAuthConfiguration.java
> testing s2s key

- Jenkinsfile_CNP
- src/main/resources/application.yml
- src/main/resources/bootstrap.yaml
> Corrected s2s issue

- charts/probate-orchestrator-service/Chart.yaml
> Added new version

- build.gradle
- src/main/resources/bootstrap.yaml
> Add properties jar. Clean up

- src/main/java/uk/gov/hmcts/probate/security/ServiceAuthConfiguration.java
> Remove debug logging

- src/main/resources/bootstrap.yaml
> Update appinsights env var

- Jenkinsfile_CNP
> ASE in both AAT & PROD.

- src/main/resources/bootstrap.yaml
> Revert update appinsights env var

- Jenkinsfile_CNP
> ASE To AKS Migration

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
- src/main/java/uk/gov/hmcts/probate/core/service/SecurityUtils.java
- src/main/java/uk/gov/hmcts/probate/security/ServiceAuthConfiguration.java
- src/main/resources/application.yml
> Corrected  log levels

- build.gradle
- charts/probate-orchestrator-service/values.yaml
https://tools.hmcts.net/jira/browse/PRO-6545
Not updating when executor has disagreed to declaration
```
[ ] Yes
[x] No
```
> PRO-6545: Not updating when executor has disagreed to declaration

- build.gradle
> PRO-6602: Fix Sonar Coverage

- build.gradle
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/LegacyExecutorsMapper.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/LegacyIntestacyMapper.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/LegacyPaMapper.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/ToLegacyExecutorApplyingCollectionMember.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/ToLegacyExecutorNotApplyingCollectionMember.java
- src/main/java/uk/gov/hmcts/probate/utils/ScheduledConfiguration.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/LegacyIntestacyMapperTest.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/LegacyPaMapperTest.java
- src/test/resources/legacyPaForm.json
> PRO-6602: Fix executor migration issue

- src/main/java/uk/gov/hmcts/probate/core/service/mapper/IntestacyMapper.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/migration/LegacyIntestacyMapper.java
Added missing maps for intestacy fields
> PRO-6653: added missing legacy fields

- build.gradle
> PRO-6548: Restore sonar exclusions

- build.gradle
https://tools.hmcts.net/jira/browse/PRO-6683
Add submit warning to invites
```
[ ] Yes
[x] No
```
> PRO-6683: Update commons version

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
https://tools.hmcts.net/jira/browse/PRO-7825
Serenity Implementation and added back the ignored test cases
```
[ ] Yes
[X ] No
```
> PRO-7825 Serenity Implementation

- Jenkinsfile_parameterized
- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-631
Owasp versions changes
```
[ ] Yes
[X ] No
```
> Owasp version changes2

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
reverted back the values.yml for the PR env that accidently merged to master
```
[ ] Yes
[x] No
```
> reverted back the API_URL to env

- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/InvitationControllerFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/utils/TestUtils.java
- src/functionalTest/resources/json/GoPForm_Full.json
- src/functionalTest/resources/json/payment.json
https://tools.hmcts.net/jira/browse/DTSPB-815
Added new validations endpoints tests in FormController
```
[ ] Yes
[ x] No
```
> New validations tests in Form Controller

- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/InvitationControllerFunctionalTests.java
https://tools.hmcts.net/jira/browse/DTSPB-822
Invitation Controller pending tag tests fixed.
```
[ ] Yes
[x ] No
```
> Fixing Pending tag tests in Invitation Controller Functional Tests

- dependency-check-suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/InvitationControllerFunctionalTests.java
- src/functionalTest/resources/json/PaymentDtoTest.json
- src/functionalTest/resources/json/caveatForm.json
- src/functionalTest/resources/json/submissionForm.json
- src/functionalTest/resources/json/submitPaymentDto.json
- src/functionalTest/resources/json/updatePaymentFormWithInvalidPaymentStatus.json
- src/functionalTest/resources/json/validInvitation.json
- src/functionalTest/resources/json/validInvitationWithInviteId.json
> Payments submissions tests

- dependency-check-suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/InvitationControllerFunctionalTests.java
- src/functionalTest/resources/json/PaymentDtoTest.json
- src/functionalTest/resources/json/caveatForm.json
- src/functionalTest/resources/json/submissionForm.json
- src/functionalTest/resources/json/submitPaymentDto.json
- src/functionalTest/resources/json/updatePaymentFormWithInvalidPaymentStatus.json
- src/functionalTest/resources/json/validInvitation.json
- src/functionalTest/resources/json/validInvitationWithInviteId.json
DTSPB-815
Add new functional tests for form controller in orchestrator service
Add payments and submission api functional test for Form Controller 
```
[ ] Yes
[X ] No
```
> Add forms submissions and payment test

- dependency-check-suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/InvitationControllerFunctionalTests.java
> DTSPB-813:force pr build

- build.gradle
- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
- dependency-check-suppressions.xml
- src/functionalTest/resources/json/GoPForm_Full.json
- src/functionalTest/resources/json/GoPForm_partial.json
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/IntestacyMapper.java
- src/main/java/uk/gov/hmcts/probate/core/service/mapper/PaMapper.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/IntestacyTestDataCreator.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/PaMultipleExecutorTestDataCreator.java
- src/test/java/uk/gov/hmcts/probate/core/service/mapper/PaSingleExecutorTestDataCreator.java
https://tools.hmcts.net/jira/browse/DTSPB-529
New death cert flow
```
[ ] Yes
[x] No
```
> Dtspb 529 new death cert flow changes

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
n/a
correct the values pushed in values.yaml as SB upgrade
```
[ ] Yes
[ X ] No
```
> Correct the urls for other services in orch values.yaml

- src/functionalTest/java/uk/gov/hmcts/probate/functional/tests/FormsFunctionalTests.java
- src/functionalTest/java/uk/gov/hmcts/probate/functional/utils/TestUtils.java
- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
- src/test/java/uk/gov/hmcts/probate/core/service/SubmitServiceImplTest.java
https://tools.hmcts.net/jira/browse/DTSPB-698
remove duplicate ccd call
```
[ ] Yes
[x] No
```
> Refactor update method to only call ccd once

- dependency-check-suppressions.xml
DTSPB-698: fixing the build errorr
```
[ ] Yes
[x] No
```
> fixing the cve build error

- build.gradle
- dependency-check-suppressions.xml
DTSPB-1233
Update dependency versions and rewrite suppression file
```
[ ] Yes
[ X ] No
```
> DTSPB-1233 Update dependency versions and rewrite suppression file

- dependency-check-suppressions.xml
> DTSPB-1380 dependencies added.

- dependency-check-suppressions.xml
- src/main/resources/application.yml
Effectively disable the Awaiting docs scheduled job
> DTSPB-1659: set waiting docs to only run on 1st Jan

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1647
https://tools.hmcts.net/jira/browse/DTSPB-1543
resolve bouncycastle suppression
```
[ ] Yes
[X ] No
```
> DTSPB-1647 resolve bouncycastle suppression

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1650
https://tools.hmcts.net/jira/browse/DTSPB-1652
changes to resolve supressions
[ ] Yes
[X ] No
> DTSPB-1650+52 resolve suppressions for beanutils and httpclient

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1649
CVE resolution
```
[ ] Yes
[X ] No
```
> DTSPB-1649 tomcat related suppressions resolution

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1686
CVE resolution
```
[ ] Yes
[ X ] No
```
> DTSPB-1686 Resolve CVE-2021-22112 suppression

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1651
added junit upper version as a transitive dependencies to resolve suppression
[ ] Yes
[ X ] No
> DTSPB-1651 Resolve CVE-2020-15250 Junit

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-1716
Resolve CEW79 suppression
```
[ ] Yes
[X ] No
```
> DTSPB-1716 Resolve CWE79 suppression

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-1775
Update probate commons version
```
[ ] Yes
[X] No
```
> DTSPB-1775 update commons version

- charts/probate-orchestrator-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-1843
Updated the API versions in the charts yml file
```
[ ] Yes
[X] No
```
> DTSPB-1843 Updated java chart version

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-1863
resolve cve suppression than suppressing it 
```
[ ] Yes
[ X] No
```
> DTSPB-1863 resolve the commons-io cve

- build.gradle
DTSPB-1818
migrating to jitpack
```
[ ] Yes
[ ] No
```
> migrating to jitpack

- src/main/java/uk/gov/hmcts/probate/controller/FormsController.java
- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
https://tools.hmcts.net/jira/browse/DTSPB-1869
removed unnecessary logs
```
[ ] Yes
[X] No
```
> DTSPB-1869-remove-logs

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-1526
bump probate-commons
```
[ ] Yes
[x] No
```
> DTSPB-1526: bump probate-commons

- build.gradle
prod issue debugging
Revert commons version for lev
```
[ ] Yes
[X ] No
```
> Revert probate commons tag version to non lev changes

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSPB-2020
code changes to sync all branches to master with every deployment
[ ] Yes
[ X ] No
> DTSPB-2020 Sync master code to all env when with every merge

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-2095
Fix CVE-2021-22118
[ ] Yes
[ X ] No
> DTSPB-2095 Fix CVE-2021-22118

- src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
https://tools.hmcts.net/jira/browse/DTSPB-2087
Add logs for further investigation
```
[ ] Yes
[X] No
```
> DTSPB-2087 Add logs for getInviteData

- src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
logs added for investigation
```
[ ] Yes
[X] No
```
> DTSPB-2087 log added.

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-2176
```
[ ] Yes
[ ] No
```
> DTSPB-2175 update Dependencies

- build.gradle
- dependency-check-suppressions.xml
DTSPB-2175
close open dependabot prs 
```
[ ] Yes
[ X ] No
```
> DTSPB-2175 Dependabot open PRs fix

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-2221
Update tomcat version and fix nightly
[ ] Yes
[X ] No
> DTSPB-2221 Upgrade tomcat version to fix dep failure

- security.sh
https://tools.hmcts.net/jira/browse/DTSPB-2177
Add security script
```
[ ] Yes
[x] No
```
> DTSPB-2177: add security script for nightly tests

- build.gradle
- security.sh
https://tools.hmcts.net/jira/browse/DTSPB-2177
Fix swagger
```
[ ] Yes
[x] No
```
> DTSPB-2177: fix swagger

- audit.json
https://tools.hmcts.net/jira/browse/DTSPB-2177
Fix
```
[ ] Yes
[x] No
```
> DTSPB-2177: fix

- dependency-check-suppressions.xml
N/A
Suppress CVE until spring boot upgrade
[ ] Yes
[x] No
> suppress CVE until spring boot upgrade

- charts/probate-orchestrator-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-2276
- Bump chart.yaml java version to 3.6.0
```
[ ] Yes
[x] No
```
> DTSPB-2276 - Bump chart.yaml java version to 3.6.0

- build.gradle
- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
> Fix post tc issue

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
> Fix Build issues ,correct urls

- build.gradle
- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
- dependency-check-suppressions.xml
- gradlew
- gradlew.bat
- src/main/java/uk/gov/hmcts/probate/core/service/DataExtractDateValidator.java
- src/main/resources/application.yml
- src/main/resources/bootstrap.yaml
This reverts commit dc2b5154e2ef3fb660250d752acfa1caf1b68d2f.
```
[ ] Yes
[x] No
```
> Revert "Dtspb 1867 2 try again (#617)"

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-2450
fix cve issue
[ ] Yes
[x] No
> DTSPB-2450 fix cve

- src/functionalTest/resources/application.properties
N/A
Change email address in tests
```
[ ] Yes
[x] No
```
> Change citizen user email in tests

- charts/probate-orchestrator-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-2584
```
[ ] Yes
[ x] No
```
> DTSPB-2584: Resolve the below deprecated warning form Java repos

- build.gradle
DTSPB-2604
fix dep failure issue
[ ] Yes
[ X] No
> DTSPB-2604 Fix Dep failure

- README.md
https://tools.hmcts.net/jira/browse/DTSPB-2556
Whitespace change to kick pod
```
[] Yes
[x] No
```
> DTSPB-2556: Break property name for test

- charts/probate-orchestrator-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-2642
[ ] Yes
[ X ] No
> DTSPB-2642 Java chart version upgrade

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/DTSPB-2616
Serenity report generation fix
```
[ ] Yes
[X ] No
```
> DTSPB-2616 Serenity report generation fix

- audit.json
- security.sh
> Dtspb 2645 revert

- build.gradle
- dependency-check-suppressions.xml
> DTSPB-2801: resolved CVE

- src/test/java/uk/gov/hmcts/probate/core/service/task/ScheduledTaskRunnerTest.java
- src/test/java/uk/gov/hmcts/probate/schedule/SmeeAndFordExtractTaskTest.java
additional changes for Scehduler updates
> DTSPB-2837: fixing additional tests

- dependency-check-suppressions.xml
DTSPB-2896
```
[ ] Yes
[ ] No
```
> DTSPB-2896 Update dependency-check-suppressions.xml

- charts/probate-orchestrator-service/Chart.yaml
- charts/probate-orchestrator-service/values.yaml
DTSPB-3041
Revert values.yaml point to prod
```
[ ] Yes
[x] No
```
> DTSPB-3041 revert values.yaml

- dependency-check-suppressions.xml
DTSPB-3261
```
[ ] Yes
[x] No
```
> DTSPB-3261 CVE suppression

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-3390
```
[ ] Yes
[ ] No
```
> DTSPB-3390: added suppressions

- Dockerfile
https://tools.hmcts.net/jira/browse/DTSPB-3523
update dockerfile java base image
```
[ ] Yes
[x] No
```
> DTSPB-3523 update dockerfile java base image

- audit.json
https://tools.hmcts.net/jira/browse/DTSPB-3532
```
[ ] Yes
[x] No
```
> DTSPB-3532 Suppress Security scan vulnerabilities

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPB-3906
suppress CVE-2023-33202
- [ x] Does this PR introduce a breaking change
> DTSPB-3906 suppress CVE-2023-33202

- src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
See [DTSPB-4439](https://tools.hmcts.net/jira/browse/DTSPB-4439)
Remove log calls from BusinessServiceImpl
> DTSPB-4439 do not log auth tokens

- charts/probate-orchestrator-service/Chart.yaml
Resolves: https://tools.hmcts.net/jira/browse/DTSPB-4586
> DTSPB-4586 set helm to use UCI link

- src/main/java/uk/gov/hmcts/probate/core/service/BusinessServiceImpl.java
- src/main/java/uk/gov/hmcts/probate/core/service/SubmitServiceImpl.java
- src/test/java/uk/gov/hmcts/probate/core/service/BusinessServiceImplTest.java
- src/test/java/uk/gov/hmcts/probate/core/service/SubmitServiceImplTest.java
[DTSPB-4896](https://tools.hmcts.net/jira/browse/DTSPB-4896)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> DTSPB-4896 Change getCase to getCaseId
